# Generated by Django 6.0.3 on 2026-03-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('estimated_hours', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('postponed', 'Postponed')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
