# Generated by Django 6.0.3 on 2026-03-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('daily_hours_limit', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
